### ISSUE TITLE
MessageBodyReader not found

### ISSUE THREAD

**Issue by alchekroun** [UFR27/M1_FRAMEWORK_EJB#5]
Bonjour Monsieur @nherbaut ,

Dans notre RestClientApp on reçoit une erreur de type MessageBodyReader lorsque nous faisons un readEntity sur une réponse de GET. Pourriez-vous nous aider ?

branche : developpement
Envoi de la requête get : RestClientApp:75
readEnityt: RestClientApp:77

Merci d'avance.

**Comment by nherbaut** [comment]
Avez vous ajouté la déclaration de l'élément dans le xsd ? https://stackoverflow.com/questions/1514110/how-to-generate-xmlrootelement-classes-for-base-types-in-xsd

**Comment by alchekroun** [comment]
Oui notre document .xsd ressemble exactement à cela.

La déclaration des élements dans un premier temps :
	<xsd:element name="train" type="Train"></xsd:element>

Puis dans un second temps :
<xsd:complexType name="Train">
		<xsd:sequence>
			<xsd:element name="idTrain" type="xsd:int"></xsd:element>
			<xsd:element name="nomTrain" type="xsd:string"></xsd:element>
			<xsd:element name="direction" type="Arret"></xsd:element>
			<xsd:element name="direction_type" type="xsd:string"></xsd:element>
			<xsd:element name="numeroTrain" type="xsd:int"></xsd:element>
			<xsd:element name="reseau" type="xsd:string"></xsd:element>
			<xsd:element name="statut" type="xsd:string"></xsd:element>
			<xsd:element name="base_depart_temps" type="SimpleDate"></xsd:element>
			<xsd:element name="base_arrivee_temps" type="SimpleDate"></xsd:element>
			<xsd:element name="reel_depart_temps" type="SimpleDate"></xsd:element>
			<xsd:element name="reel_arrivee_temps" type="SimpleDate"></xsd:element>
			<xsd:element name="listeArrets" type="Arret"
				maxOccurs="unbounded"></xsd:element>
			<xsd:element name="listePassager" type="Passager"
				maxOccurs="unbounded"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>

**Comment by nherbaut** [comment]
```[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/nherbaut/tmp/M1_FRAMEWORK_EJB/project-jee8-webapp/src/main/java/fr/pantheonsorbonne/ufr27/miage/mapper/TrainMapper.java:[34,25] cannot find symbol
  symbol:   method setListeArrets(java.util.List<fr.pantheonsorbonne.ufr27.miage.model.jaxb.Arret>)
  location: variable trainDTO of type fr.pantheonsorbonne.ufr27.miage.model.jaxb.Train
[ERROR] /home/nherbaut/tmp/M1_FRAMEWORK_EJB/project-jee8-webapp/src/main/java/fr/pantheonsorbonne/ufr27/miage/mapper/TrainMapper.java:[40,25] cannot find symbol
  symbol:   method setListePassagers(java.util.List<fr.pantheonsorbonne.ufr27.miage.model.jaxb.Passager>)
  location: variable trainDTO of type fr.pantheonsorbonne.ufr27.miage.model.jaxb.Train
[INFO] 2 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for project-jee8 1.0-SNAPSHOT:
[INFO] 
[INFO] project-jee8 ....................................... SUCCESS [  0.067 s]
[INFO] project-jee8-model ................................. SUCCESS [  1.365 s]
[INFO] project-jee8-webapp ................................ FAILURE [  0.559 s]
[INFO] project-jee8-rest-client ........................... SKIPPED
[INFO] project-jee8-jms-subscriber ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.105 s
[INFO] Finished at: 2020-12-06T18:12:11+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project project-jee8-webapp: Compilation failure: Compilation failure: 
[ERROR] /home/nherbaut/tmp/M1_FRAMEWORK_EJB/project-jee8-webapp/src/main/java/fr/pantheonsorbonne/ufr27/miage/mapper/TrainMapper.java:[34,25] cannot find symbol
[ERROR]   symbol:   method setListeArrets(java.util.List<fr.pantheonsorbonne.ufr27.miage.model.jaxb.Arret>)
[ERROR]   location: variable trainDTO of type fr.pantheonsorbonne.ufr27.miage.model.jaxb.Train
[ERROR] /home/nherbaut/tmp/M1_FRAMEWORK_EJB/project-jee8-webapp/src/main/java/fr/pantheonsorbonne/ufr27/miage/mapper/TrainMapper.java:[40,25] cannot find symbol
[ERROR]   symbol:   method setListePassagers(java.util.List<fr.pantheonsorbonne.ufr27.miage.model.jaxb.Passager>)
[ERROR]   location: variable trainDTO of type fr.pantheonsorbonne.ufr27.miage.model.jaxb.Train
[ERROR] -> [Help 1]
```

**Comment by alchekroun** [comment]
Excusez nous, le xsd ne génère pas les setListeArret et setListePassager. Ils font donc générer le getter et setter sur le : 
project-jee8-model/target/generated-sources/jaxb/fr/pantheonsorbonne/ufr27/miage/model/jaxb/Train.java

à chaque fois le temps que nous résolvons ce problème.

**EDIT : J'ai mis en commentaire les appels de ces méthodes. On peut de nouveau mvn package ou mvn clean package sans erreur sur la branche developpement.**

**Comment by nherbaut** [comment]
Vous n'avez pas le droit de modifier ces classes.
Pourquoi ne pas utiliser getListePassagers().addAll( otherCollection) ?

**Comment by alchekroun** [comment]
En effet, nous pouvons le faire mais pour garder le code harmonieux je pensais qu'il était préférable d’utiliser un setter directement.
